apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: snapshots.devin.baby
spec:
  group: devin.baby
  scope: Namespaced
  names:
    plural: snapshots
    singular: snapshot
    kind: Snapshot
    shortNames:
      - snap
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Runtime
          type: string
          jsonPath: .spec.runtime
        - name: Version
          type: string
          jsonPath: .status.version
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [runtime]
              properties:
                runtime:
                  type: string
            status:
              type: object
              properties:
                version:
                  type: string
                path:
                  type: string
                message:
                  type: string
