apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devin-server
  namespace: devin-app
spec:
  dataFrom:
    - extract:
        key: staging/server
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
