apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devin-server
  namespace: devin-app
spec:
  dataFrom:
    - extract:
        key: staging/server
  target:
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        SCHEDULER_URL: http://devin-brain:9092
        BETTER_AUTH_URL: https://staging-api.devin.baby
        WEB_APP_URL: https://staging.devin.baby
