apiVersion: v1
kind: Namespace
metadata:
  name: devin-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: devin-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: devin-sandboxes
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: devin-firecracker
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
