apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/external
  - ../../base/postgres/external-secret.yaml
  - ../../base/postgres/statefulset.yaml
  - ../../base/brain/deployment.yaml
  - ../../base/brain/external-secret.yaml
  - ../../base/platform/configmap.yaml
  - firecracker-hosts.yaml

patches:
  - path: patch-external-secret.yaml
  - path: patch-server-database.yaml

images:
  - name: devin-orchestrator
    newName: rshdhere/devin-orchestrator
    newTag: 1c65b8fa10ef6d246da1d02e697696be0bb2d98b
  - name: devin-server
    newName: rshdhere/devin-server
    newTag: 1c65b8fa10ef6d246da1d02e697696be0bb2d98b
  - name: devin-web
    newName: rshdhere/devin-web
    newTag: 1c65b8fa10ef6d246da1d02e697696be0bb2d98b
  - name: devin-brain
    newName: rshdhere/devin-brain
    newTag: 1c65b8fa10ef6d246da1d02e697696be0bb2d98b

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: devin
      app.kubernetes.io/managed-by: argocd
