apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devin-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rshdhere/ops.git
    targetRevision: HEAD
    path: staging/devin/overlays/external
  destination:
    server: https://kubernetes.default.svc
    namespace: devin-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: devin.baby
      kind: FirecrackerHost
      jqPathExpressions:
        - .status
